language : android
sudo: false

env:
  global :
    - ANROID_API_LEVEL = "27"
    - EMULATOR_API_LEVEL=26


android :
  components :
    - tools
    - platform-tools
    - tools
    - android - $ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
  licences :
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
